blank_issues_enabled: false

contact_links:
  - name: 📖 Documentação
    url: https://github.com/MatchDock/match-tech/blob/main/CONTRIBUTING.md
    about: Consulte a documentação antes de abrir uma issue.
